---
version: '3'
services:
  dvwa:
    image: dvwa
    build:
      context: ./.
      dockerfile: dvwa.Dockerfile
    ports:
      - '80:80'
    networks:
      main:
        aliases:
          - dvwa

  fast:
    image: wallarm/fast
    environment:
      WALLARM_API_TOKEN: ${TOKEN}
      WALLARM_API_HOST: api.wallarm.com
      CI_MODE: recording
      TEST_RUN_POLICY_ID: 215
      ALLOWED_HOSTS: dvwa
    ports:
      - '8080:8080'
    networks:
      main:
        aliases:
          - fast

  selenium:
    image: selenium/standalone-firefox:latest
    ports: ['4444:4444']
    logging:
      driver: none
    environment:
      http_proxy: http://fast:8080
    networks:
      main:
        aliases:
          - selenium

  test:
    image: test
    build:
      context: ./.
      dockerfile: test.Dockerfile
    networks:
      main:

networks:
  main:
